#!/usr/bin/env python3
"""Export API scenario DSL to a self-contained unittest/pytest-compatible suite."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from textwrap import dedent

from validate_scenarios import load_json_compatible, validate


TEST_TEMPLATE = r'''# Generated by api-scenario-automation. Edit scenarios.yaml, then regenerate.
import json
import os
import re
import unittest
from urllib import error, parse, request



SCENARIO_DOCUMENT = __SCENARIO_JSON__


class MissingPath(Exception):
    pass


def json_path(data, path):
    if path == "$":
        return data
    if not path.startswith("$."):
        raise ValueError(f"Unsupported JSON path: {path}")
    current = data
    for part in path[2:].split("."):
        while "[" in part:
            key, rest = part.split("[", 1)
            if key:
                if not isinstance(current, dict) or key not in current:
                    raise MissingPath(path)
                current = current[key]
            index_text, part = rest.split("]", 1)
            if not isinstance(current, list):
                raise MissingPath(path)
            current = current[int(index_text)]
            if part.startswith("."):
                part = part[1:]
        if part:
            if not isinstance(current, dict) or part not in current:
                raise MissingPath(path)
            current = current[part]
    return current


def render(value, variables):
    if isinstance(value, str):
        pattern = re.compile(r"\{\{\s*([A-Za-z0-9_-]+)\s*\}\}")
        def repl(match):
            name = match.group(1)
            if name not in variables:
                raise KeyError(f"Missing template variable: {name}")
            replacement = variables[name]
            if isinstance(replacement, (dict, list)):
                return json.dumps(replacement, ensure_ascii=False)
            return str(replacement)
        rendered = pattern.sub(repl, value)
        exact = re.fullmatch(r"\{\{\s*([A-Za-z0-9_-]+)\s*\}\}", value)
        if exact:
            return variables[exact.group(1)]
        return rendered
    if isinstance(value, list):
        return [render(item, variables) for item in value]
    if isinstance(value, dict):
        return {key: render(item, variables) for key, item in value.items()}
    return value


class ApiResponse:
    def __init__(self, status_code, content, headers):
        self.status_code = status_code
        self.content = content
        self.headers = headers


def http_request(method, url, headers=None, query=None, body=None, timeout=10):
    headers = dict(headers or {})
    if query:
        url = url + ("&" if "?" in url else "?") + parse.urlencode(query, doseq=True)
    data = None
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers.setdefault("Content-Type", "application/json")
    req = request.Request(url, data=data, headers=headers, method=method)
    try:
        with request.urlopen(req, timeout=timeout) as resp:
            return ApiResponse(resp.status, resp.read(), dict(resp.headers))
    except error.HTTPError as exc:
        return ApiResponse(exc.code, exc.read(), dict(exc.headers))


def assert_step(testcase, assertion, response, payload, variables):
    atype = assertion["type"]
    if atype == "status":
        expected = assertion["expected"]
        if isinstance(expected, list):
            testcase.assertIn(response.status_code, expected, f"status code {response.status_code} not in {expected}; body={response.content!r}")
        else:
            testcase.assertEqual(response.status_code, expected, f"status code mismatch; body={response.content!r}")
    elif atype == "json_path_exists":
        try:
            json_path(payload, assertion["path"])
        except MissingPath as exc:
            raise AssertionError(f"JSON path does not exist: {assertion['path']}; payload={payload!r}") from exc
    elif atype == "json_path_not_exists":
        try:
            json_path(payload, assertion["path"])
        except MissingPath:
            return
        raise AssertionError(f"JSON path exists but should not: {assertion['path']}")
    elif atype == "json_equals":
        testcase.assertEqual(json_path(payload, assertion["path"]), render(assertion["expected"], variables), f"json_equals failed at {assertion['path']}; payload={payload!r}")
    elif atype == "json_not_equals":
        testcase.assertNotEqual(json_path(payload, assertion["path"]), render(assertion["expected"], variables), f"json_not_equals failed at {assertion['path']}; payload={payload!r}")
    elif atype == "json_contains":
        actual = json_path(payload, assertion["path"])
        expected = str(render(assertion["expected"], variables))
        testcase.assertIn(expected, str(actual), f"json_contains failed at {assertion['path']}; actual={actual!r}")
    elif atype == "json_length":
        actual = json_path(payload, assertion["path"])
        testcase.assertEqual(len(actual), int(render(assertion["expected"], variables)), f"json_length failed at {assertion['path']}; actual={actual!r}")
    elif atype == "var_equals":
        testcase.assertEqual(variables[assertion["name"]], render(assertion["expected"], variables), f"var_equals failed for {assertion['name']}; variables={variables!r}")
    else:
        raise AssertionError(f"Unsupported assertion type: {atype}")


def response_json(response):
    if not response.content:
        return None
    return json.loads(response.content.decode("utf-8"))


class ApiScenarioTest(unittest.TestCase):
    maxDiff = None


def run_scenario(testcase, scenario):
    base_url = os.environ.get("API_BASE_URL") or SCENARIO_DOCUMENT.get("base_url", "")
    timeout = float(os.environ.get("API_TIMEOUT", "10"))
    variables = {}
    variables.update(SCENARIO_DOCUMENT.get("variables", {}))
    variables.update(scenario.get("variables", {}))
    for step in scenario["steps"]:
        req = step["request"]
        method = req["method"].upper()
        url = base_url.rstrip("/") + render(req["path"], variables)
        with testcase.subTest(step=step["id"], name=step["name"], method=method, url=url):
            response = http_request(
                method,
                url,
                headers=render(req.get("headers", {}), variables),
                query=render(req.get("query", {}), variables),
                body=render(req["body"], variables) if "body" in req else None,
                timeout=timeout,
            )
            try:
                payload = response_json(response)
            except ValueError:
                payload = None

            for assertion in step.get("assert", []):
                assert_step(testcase, assertion, response, payload, variables)

            for name, path in step.get("extract", {}).items():
                try:
                    variables[name] = json_path(payload, path)
                except MissingPath as exc:
                    raise AssertionError(f"extract failed for variable {name} at {path}; payload={payload!r}") from exc


def _make_test(scenario):
    def test(self):
        run_scenario(self, scenario)
    slug = re.sub(r"[^A-Za-z0-9_]+", "_", scenario["name"]).strip("_") or "scenario"
    test.__name__ = "test_" + slug
    return test


for index, scenario in enumerate(SCENARIO_DOCUMENT["scenarios"], start=1):
    slug = re.sub(r"[^A-Za-z0-9_]+", "_", scenario["name"]).strip("_") or "scenario"
    name = "test_%02d_%s" % (index, slug)
    setattr(ApiScenarioTest, name, _make_test(scenario))


if __name__ == "__main__":
    unittest.main()
'''


README_TEMPLATE = """# Generated API Automation

This directory was generated by `api-scenario-automation`.

## Run

```bash
API_BASE_URL=http://127.0.0.1:4273 python3 -m unittest discover tests
```

Edit `scenarios.yaml`, validate it, then regenerate tests:

```bash
python3 <skill>/scripts/validate_scenarios.py scenarios.yaml
python3 <skill>/scripts/export_pytest.py scenarios.yaml --output api-automation
```
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Export scenario DSL to pytest.")
    parser.add_argument("input", type=Path)
    parser.add_argument("--output", "-o", type=Path, required=True)
    args = parser.parse_args()

    data = load_json_compatible(args.input)
    errors = validate(data)
    if errors:
        for error in errors:
            print(f"error: {error}")
        return 1

    out = args.output
    tests = out / "tests"
    tests.mkdir(parents=True, exist_ok=True)
    (out / "scenarios.yaml").write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    test_code = TEST_TEMPLATE.replace(
        "__SCENARIO_JSON__",
        repr(data),
    )
    (tests / "test_api_scenarios.py").write_text(dedent(test_code), encoding="utf-8")
    (out / "README.generated.md").write_text(README_TEMPLATE, encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
